primary_key: uid
fields:
  uid: uid
  anno_cargue_secop: anno_cargue_secop
  anno_firma_contrato: anno_firma_contrato
  nivel_entidad: nivel_entidad
  orden_entidad: orden_entidad
  nombre_entidad: nombre_entidad
  nit_de_la_entidad: nit_de_la_entidad
  c_digo_de_la_entidad: c_digo_de_la_entidad
  id_modalidad: id_modalidad
  modalidad_de_contratacion: modalidad_de_contratacion
  estado_del_proceso: estado_del_proceso
  causal_de_otras_formas_de: causal_de_otras_formas_de
  id_regimen_de_contratacion: id_regimen_de_contratacion
  nombre_regimen_de_contratacion: nombre_regimen_de_contratacion
  id_objeto_a_contratar: id_objeto_a_contratar
  objeto_a_contratar: objeto_a_contratar
  detalle_del_objeto_a_contratar: detalle_del_objeto_a_contratar
  tipo_de_contrato: tipo_de_contrato
  municipio_de_obtencion: municipio_de_obtencion
  municipio_de_entrega: municipio_de_entrega
  municipios_ejecucion: municipios_ejecucion
  fecha_de_cargue_en_el_secop: fecha_de_cargue_en_el_secop
  numero_de_constancia: numero_de_constancia
  numero_de_proceso: numero_de_proceso
  numero_de_contrato: numero_de_contrato
  cuantia_proceso: cuantia_proceso
  id_grupo: id_grupo
  nombre_grupo: nombre_grupo
  id_familia: id_familia
  nombre_familia: nombre_familia
  id_clase: id_clase
  nombre_clase: nombre_clase
  id_adjudicacion: id_adjudicacion
  tipo_identifi_del_contratista: tipo_identifi_del_contratista
  identificacion_del_contratista: identificacion_del_contratista
  nom_razon_social_contratista: nom_razon_social_contratista
  dpto_y_muni_contratista: dpto_y_muni_contratista
  tipo_doc_representante_legal: tipo_doc_representante_legal
  identific_representante_legal: identific_representante_legal
  nombre_del_represen_legal: nombre_del_represen_legal
  fecha_de_firma_del_contrato: fecha_de_firma_del_contrato
  fecha_ini_ejec_contrato: fecha_ini_ejec_contrato
  plazo_de_ejec_del_contrato: plazo_de_ejec_del_contrato
  rango_de_ejec_del_contrato: rango_de_ejec_del_contrato
  tiempo_adiciones_en_dias: tiempo_adiciones_en_dias
  tiempo_adiciones_en_meses: tiempo_adiciones_en_meses
  fecha_fin_ejec_contrato: fecha_fin_ejec_contrato
  compromiso_presupuestal: compromiso_presupuestal
  cuantia_contrato: cuantia_contrato
  valor_total_de_adiciones: valor_total_de_adiciones
  valor_contrato_con_adiciones: valor_contrato_con_adiciones
  objeto_del_contrato_a_la: objeto_del_contrato_a_la
  proponentes_seleccionados: proponentes_seleccionados
  calificacion_definitiva: calificacion_definitiva
  id_sub_unidad_ejecutora: id_sub_unidad_ejecutora
  nombre_sub_unidad_ejecutora: nombre_sub_unidad_ejecutora
  ruta_proceso_en_secop_i: ruta_proceso_en_secop_i
  moneda: moneda
  es_postconflicto: es_postconflicto
  marcacion_adiciones: marcacion_adiciones
  posicion_rubro: posicion_rubro
  nombre_rubro: nombre_rubro
  valor_rubro: valor_rubro
  sexo_replegal: sexo_replegal
  pilar_acuerdo_paz: pilar_acuerdo_paz
  punto_acuerdo_paz: punto_acuerdo_paz
  municipio_entidad: municipio_entidad
  departamento_entidad: departamento_entidad
  ultima_actualizacion: ultima_actualizacion
  fecha_liquidacion: fecha_liquidacion
  cumpledecreto248: cumpledecreto248
  incluyebienesdecreto248: incluyebienesdecreto248
  cumple_sentencia_t302: cumple_sentencia_t302
  es_mipyme: es_mipyme
  tama_o_mipyme: tama_o_mipyme
  codigo_bpin: codigo_bpin
  destino_gasto: destino_gasto
  pliegos_tipo: pliegos_tipo
  sector_pliegos_tipo: sector_pliegos_tipo
system_fields:
  updated_at: ":updated_at"
export_exclude:
  - uid
  - anno_cargue_secop
  - nivel_entidad
  - orden_entidad
  - nombre_entidad
  - nit_de_la_entidad
  - c_digo_de_la_entidad
  - id_modalidad
  - causal_de_otras_formas_de
  - id_regimen_de_contratacion
  - nombre_regimen_de_contratacion
  - id_objeto_a_contratar
  - municipio_de_obtencion
  - municipio_de_entrega
  - municipios_ejecucion
  - fecha_de_cargue_en_el_secop
  - numero_de_constancia
  - id_grupo
  - nombre_grupo
  - id_familia
  - nombre_familia
  - id_clase
  - nombre_clase
  - id_adjudicacion
  - dpto_y_muni_contratista
  - id_sub_unidad_ejecutora
  - nombre_sub_unidad_ejecutora
  - ruta_proceso_en_secop_i
  - moneda
  - es_postconflicto
  - marcacion_adiciones
  - posicion_rubro
  - nombre_rubro
  - valor_rubro
  - sexo_replegal
  - pilar_acuerdo_paz
  - punto_acuerdo_paz
select:
  - uid
  - anno_cargue_secop
  - anno_firma_contrato
  - nivel_entidad
  - orden_entidad
  - nombre_entidad
  - nit_de_la_entidad
  - c_digo_de_la_entidad
  - id_modalidad
  - modalidad_de_contratacion
  - estado_del_proceso
  - causal_de_otras_formas_de
  - id_regimen_de_contratacion
  - nombre_regimen_de_contratacion
  - id_objeto_a_contratar
  - objeto_a_contratar
  - detalle_del_objeto_a_contratar
  - tipo_de_contrato
  - municipio_de_obtencion
  - municipio_de_entrega
  - municipios_ejecucion
  - fecha_de_cargue_en_el_secop
  - numero_de_constancia
  - numero_de_proceso
  - numero_de_contrato
  - cuantia_proceso
  - id_grupo
  - nombre_grupo
  - id_familia
  - nombre_familia
  - id_clase
  - nombre_clase
  - id_adjudicacion
  - tipo_identifi_del_contratista
  - identificacion_del_contratista
  - nom_razon_social_contratista
  - dpto_y_muni_contratista
  - tipo_doc_representante_legal
  - identific_representante_legal
  - nombre_del_represen_legal
  - fecha_de_firma_del_contrato
  - fecha_ini_ejec_contrato
  - plazo_de_ejec_del_contrato
  - rango_de_ejec_del_contrato
  - tiempo_adiciones_en_dias
  - tiempo_adiciones_en_meses
  - fecha_fin_ejec_contrato
  - compromiso_presupuestal
  - cuantia_contrato
  - valor_total_de_adiciones
  - valor_contrato_con_adiciones
  - objeto_del_contrato_a_la
  - proponentes_seleccionados
  - calificacion_definitiva
  - id_sub_unidad_ejecutora
  - nombre_sub_unidad_ejecutora
  - ruta_proceso_en_secop_i
  - moneda
  - es_postconflicto
  - marcacion_adiciones
  - posicion_rubro
  - nombre_rubro
  - valor_rubro
  - sexo_replegal
  - pilar_acuerdo_paz
  - punto_acuerdo_paz
  - municipio_entidad
  - departamento_entidad
  - ultima_actualizacion
  - fecha_liquidacion
  - cumpledecreto248
  - incluyebienesdecreto248
  - cumple_sentencia_t302
  - es_mipyme
  - tama_o_mipyme
  - codigo_bpin
  - destino_gasto
  - pliegos_tipo
  - sector_pliegos_tipo
  - ":updated_at"
